### ISSUE TITLE
Ability to select fonts in which modules are displayed in.

### ISSUE THREAD

**Issue by Parmjot-Singh** [nwg-piotr/nwg-panel#101]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there are like 3 fonts used in my panel, and I like none of them.

**Describe the solution you'd like**
Allow the user to change the font in which things are displayed.

**Describe alternatives you've considered**
You tell me...

**Additional context**
![image](https://user-images.githubusercontent.com/100116708/162111286-f243fc83-206b-4b90-8418-52f852abfe67.png)
What even is that

**Comment by nwg-piotr** [comment]
> You tell me...

Redefine css to your liking.

```css
/* Executors usually behave better in monospace fonts */
#executor-label {
    font-family: monospace;
    font-size: 16px
}

/* Sample executor-weather uses "css-name": "weather" */
#weather {
    font-size: 16px
}
```
