### ISSUE TITLE
Questions about the Hyprland workspace and controls

### ISSUE THREAD

**Issue by Quasar-0330** [nwg-piotr/nwg-panel#335]
When I hover the mouse over a Hyprland workspace or control, I see a blue border, can I change the color of that border?
I have tried `#hyprland-workspaces-item:hover` and others, but cannot change it.

**Comment by nwg-piotr** [comment]
This is related to the theme you use. You could try to (re)define this:

```css
/* Selected (hovered) UI elements */
*:selected {
  border: none;
  background: #cd7ebf;
  color: #fff
}
```
