### ISSUE TITLE
Border color when hovering over some buttons

### ISSUE THREAD

**Issue by Quasar-0330** [nwg-piotr/nwg-panel#385]
![Image](https://github.com/user-attachments/assets/b04b4f6e-1582-4c56-ade8-d20964fdd0bc)

The buttons in the image show a blue border when hovered over with the mouse, can the color be changed? I tried elements such as `#controls-overview` and `#controls-overview:hover`, but could not change it.

**Comment by nwg-piotr** [comment]
Try this, adjust to your needs:

```css
/* Selected (hovered) UI elements */
*:selected {
    border: none;
    border-radius: 3px;
    background: #cd7ebf;
    color: #fff
}
```
